
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Industrial', 'industrial', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Buildings and Trades', 'buildings-and-trades', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Cosmetology', 'cosmetology', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Criminal Justice', 'criminal-justice', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Health Science', 'health-science', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('HVAC', 'hvac', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Mobile Equipment', 'mobile-equipment', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Utility Line Technician', 'utility-line-technician', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Welding', 'welding', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Computers', 'computers', NULL);
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Analyzers', 'analyzers', (SELECT id FROM public.categories WHERE slug='industrial'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Electrical', 'electrical', (SELECT id FROM public.categories WHERE slug='industrial'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Instrumentation', 'instrumentation', (SELECT id FROM public.categories WHERE slug='industrial'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Process Technology', 'process-technology', (SELECT id FROM public.categories WHERE slug='industrial'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Cosmetology - State Board License', 'cosmetology-state-board-license', (SELECT id FROM public.categories WHERE slug='cosmetology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Anatomy & Physiology', 'anatomy-and-physiology', (SELECT id FROM public.categories WHERE slug='health-science'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('CNA', 'cna', (SELECT id FROM public.categories WHERE slug='health-science'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Medical Terminology', 'medical-terminology', (SELECT id FROM public.categories WHERE slug='health-science'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Compressors', 'compressors', (SELECT id FROM public.categories WHERE slug='process-technology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Pumps', 'pumps', (SELECT id FROM public.categories WHERE slug='process-technology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Valves', 'valves', (SELECT id FROM public.categories WHERE slug='process-technology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Cooling Towers', 'cooling-towers', (SELECT id FROM public.categories WHERE slug='process-technology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Mechanical', 'mechanical', (SELECT id FROM public.categories WHERE slug='industrial'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Distillation', 'distillation', (SELECT id FROM public.categories WHERE slug='process-technology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Intro to Process Equipment', 'intro-to-process-equipment', (SELECT id FROM public.categories WHERE slug='process-technology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Cell Structure', 'cell-structure', (SELECT id FROM public.categories WHERE slug='anatomy-and-physiology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Mapping the Body', 'mapping-the-body', (SELECT id FROM public.categories WHERE slug='anatomy-and-physiology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('The Twelve Body Systems', 'the-twelve-body-systems', (SELECT id FROM public.categories WHERE slug='anatomy-and-physiology'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Basic Instrumentation', 'basic-instrumentation', (SELECT id FROM public.categories WHERE slug='instrumentation'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Tube Bending and Fittings', 'tube-bending-and-fittings', (SELECT id FROM public.categories WHERE slug='instrumentation'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Calibration', 'calibration', (SELECT id FROM public.categories WHERE slug='instrumentation'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Maintenance', 'maintenance', (SELECT id FROM public.categories WHERE slug='instrumentation'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('HVAC Basics', 'hvac-basics', (SELECT id FROM public.categories WHERE slug='hvac'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('HVAC Performance Tasks', 'hvac-performance-tasks', (SELECT id FROM public.categories WHERE slug='hvac'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('Duct and System Design', 'duct-and-system-design', (SELECT id FROM public.categories WHERE slug='hvac'));
INSERT INTO public.categories (name, slug, parent_id) VALUES ('HVAC Components and Parts', 'hvac-components-and-parts', (SELECT id FROM public.categories WHERE slug='hvac'));
